# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Valentina Project
description: Valentina is open source pattern drafting software, designed to be the foundation of a new stack of open source tools to remake the garment industry.
baseurl: "" # the subpath of your site, e.g. /blog

url: "http://yourdomain.com" # the base hostname & protocol for your site

keywords: ['pattern making', 'open fashion', 'pattern drafting', 'pattern cutting']

googleAnalytics:

# sns
github: valentina
email: contact@valentina-project.org
twitter: valentina


# Build settings
markdown: kramdown
encoding: utf-8
exclude: [README.md, LICENSE, CNAME]

# Valentina Settings
valentina_version: 0.4.4

sass:
  sass_dir: scss
